// clientProfileColumns.ts
export const CLIENT_PROFILE_COLUMNS = new Set([
  'entity_id',
  'owner_user_id',
  'agency_user_id',
  'vertical',

  'business_name',
  'alternate_name',
  'legal_name',
  'business_url',
  'logo_url',
  'short_description',
  'long_description',
  'category',
  'year_established',
  'team_size',

  'phone',
  'email',
  'address_street',
  'address_city',
  'address_state',
  'address_postal_code',
  'hours',
  'locations',

  'license_number',
  'certifications',
  'accreditations',
  'insurance_accepted',
  'legal_profile',
  'medical_profile',

  'services',
  'practice_areas',
  'medical_specialties',

  'testimonials',
  'case_studies',
  'press_news',
  'awards',
  'faqs',
  'help_articles',
  'articles',

  'linkedin_profile',
  'facebook_profile',
  'instagram_profile',
  'youtube_profile',
  'twitter_profile',
  'tiktok_profile',
  'pinterest_profile',
  'yelp_profile',
  'bbb_profile',
  'google_business_url',
  'apple_maps_url',
  'other_profiles'
]);
